In [1]:
import pymongo
from pymongo import MongoClient
import pandas as pd
import numpy as np
import re

In [ ]:
CONNECTION_STRING = "mongodb+srv://longth:password@cluster0.tehe2.azure.mongodb.net/?retryWrites=true&w=majority"

In [3]:
client = MongoClient(CONNECTION_STRING)

In [4]:
db = client['Data_Engineer']

In [5]:
collection = db['Comments']

In [6]:
cursor = collection.find()

In [7]:
list_cur = list(cursor)

In [8]:
list_cur

[{'_id': ObjectId('555466761a77ce5d65ea062a'),
  'ranking': 0,
  'layer': 0,
  'user_id': 12,
  'like': 1,
  'user_email': 'hoaianh2210@gmail.com',
  'comment_on': 'event',
  'ip': 'null',
  'user_fullname': 'Nguyễn Hoài Anh',
  'publish_status': 1,
  'object_id': '552b2f0817dc135c89d7d6a2',
  'content': 'Chương trình \\ Tuyệt cú mèo\\ luôn, chờ lâu rồi mới có số mới, hóng hóng',
  'reviewer': 'gianpt',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431595030,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555457bf1a77ce5d65ea0617'),
  'ranking': 0,
  'layer': 0,
  'user_id': 130,
  'like': 5,
  'user_email': 'gian.phan@gmail.com',
  'comment_on': 'event',
  'ip': 'null',
  'user_fullname': 'Phan Thanh Gian',
  'publish_status': 1,
  'object_id': '552b2f0817dc135c89d7d6a2',
  'content': 'Chờ đợi chương trình này đã lâu! Hẹn mọi người tối nay lúc 8:30 trên FPT Play nhé.',
  'reviewer': 'gianpt',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431591263,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555413001a77ce5d65ea0609'),
  'ranking': 0,
  'layer': 0,
  'user_id': 527201,
  'like': 0,
  'user_email': 'cloudytang@gmail.com',
  'comment_on': 'vod',
  'ip': '42.116.8.164',
  'user_fullname': 'Đàm Ngọc Vân',
  'publish_status': 0,
  'object_id': '5453639f17dc1371f538a4cd',
  'content': 'comment cai',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431573662,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 2,
  'device_id': '983b5151a74de256'},
 {'_id': ObjectId('555357f71a77ce5d65ea0606'),
  'ranking': 0,
  'layer': 0,
  'user_id': 424467,
  'like': 1,
  'user_email': 'n_x_cuong@yahoo.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'nguyen xuan cuong',
  'publish_status': 1,
  'object_id': '551a43b417dc135c58f3c691',
  'content': 'lồng tiếng mà như tập đọc, nghe không nuốt nổi, coi phụ đề còn đở khó chịu hơn',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431525776,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555491181a77ce5d65ea0636'),
  'ranking': 0,
  'layer': 0,
  'user_id': 805,
  'like': 12,
  'user_email': 'lequy1579@gmail.com',
  'comment_on': 'vod',
  'ip': '42.117.66.148',
  'user_fullname': 'Quang Quỳnh Lê',
  'publish_status': 1,
  'object_id': '5549cace17dc132a0cee1801',
  'content': 'Phim rất hay ;)',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431605947,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '2e190e1227743c0d'},
 {'_id': ObjectId('555497151a77ce5d65ea0638'),
  'ranking': 0,
  'layer': 0,
  'user_id': 228645,
  'like': 2,
  'user_email': 'phucnguyen993@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Phúc',
  'publish_status': 1,
  'object_id': '54fd41f417dc136164a0ceda',
  'content': 'hài vãi ko tả nổi',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431607478,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('5554d4661a77ce5d65ea065f'),
  'ranking': 0,
  'layer': 0,
  'user_id': 529023,
  'like': 0,
  'user_email': 'coraline06@yahoo.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'coraline06@yahoo.com',
  'publish_status': 1,
  'object_id': '52cbcfa3c969282524444633',
  'content': 'hay thúi ruột thúi gan luôn !!!! :)))',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431623177,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('55558bef1a77ce5d65ea066f'),
  'ranking': 0,
  'layer': 0,
  'user_id': 62638,
  'like': 1,
  'user_email': 'vuluc22@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'vuluc22@gmail.com',
  'publish_status': 1,
  'object_id': '555565eb17dc132457dfbc65',
  'content': 'shittttttttttt',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431670167,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555599531a77ce5d65ea0675'),
  'ranking': 0,
  'layer': 0,
  'user_id': 117393,
  'like': 2,
  'user_email': 'hoaianh2210@yahoo.com',
  'comment_on': 'vod',
  'ip': '42.116.8.164',
  'user_fullname': 'Nguyễn Hoài Anh',
  'publish_status': 1,
  'object_id': '55555e9717dc132457dfbc62',
  'content': 'phim hay qua. xem thoi',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431673598,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '6e2c0a1180b7268d'},
 {'_id': ObjectId('5555e8871a77ce5d65ea0682'),
  'ranking': 0,
  'layer': 0,
  'user_id': 529926,
  'like': 4,
  'user_email': 'huynhhai13121994@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'huynhhai13121994@gmail.com',
  'publish_status': 1,
  'object_id': '55224d6e17dc1367d3b6c03e',
  'content': 'phim hay cuc',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431693875,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('55579ac91a77ce5d65ea06ca'),
  'ranking': 0,
  'layer': 0,
  'user_id': 533775,
  'like': -1,
  'user_email': 'lilethanhthon2@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Trịnh Minh Hùng',
  'publish_status': 1,
  'object_id': '53588319c969287b49b1b0a4',
  'content': 'Vẫn chưa có choảng mạnh lắm @',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431805057,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('5557ed541a77ce5d65ea06cf'),
  'ranking': 0,
  'layer': 0,
  'user_id': 529712,
  'like': 3,
  'user_email': 'prolove9c@yahoo.com.vn',
  'comment_on': 'vod',
  'ip': '113.174.199.57',
  'user_fullname': 'Ngô Vũ Thanh Toàn',
  'publish_status': 1,
  'object_id': '548a974717dc13572611a7eb',
  'content': 'oh my god phim hay',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431826191,
  'device': 'winphone',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'otz5TlINlr88qXIvEUhmESyzJspLsuj9IxqQK6bAUxo'},
 {'_id': ObjectId('555831241a77ce5d65ea06d9'),
  'ranking': 0,
  'layer': 0,
  'user_id': 531594,
  'like': 4,
  'user_email': 'tranduyninh2002@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'tranduyninh2002@gmail.com',
  'publish_status': 1,
  'object_id': '5440f67817dc137878244cf2',
  'content': 'quá hay, cam on admin',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431843554,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('55588bfb1a77ce5d65ea06ec'),
  'ranking': 0,
  'layer': 0,
  'user_id': 380751,
  'like': 12,
  'user_email': 'pun1512000@yahoo.com.vn',
  'comment_on': 'vod',
  'ip': '113.173.8.226',
  'user_fullname': 'Pun Diệu',
  'publish_status': 1,
  'object_id': '5215971ec969287094465754',
  'content': 'rấy hay và hấp dẫn :))',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431866813,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'fc0c686adf80bafc'},
 {'_id': ObjectId('5558ba831a77ce5d65ea06fb'),
  'ranking': 0,
  'layer': 0,
  'user_id': 535331,
  'like': 10,
  'user_email': 'lien270400@gmail.com',
  'comment_on': 'vod',
  'ip': '113.187.17.26',
  'user_fullname': 'Liên Thùy',
  'publish_status': 1,
  'object_id': '5215971ec969287094465754',
  'content': 'cập nhật mà k xemm đc j v..loading cả buổii à',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431878724,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'fc658cce60cd5787'},
 {'_id': ObjectId('555945641a77ce5d65ea070b'),
  'ranking': 0,
  'layer': 0,
  'user_id': 505937,
  'like': 1,
  'user_email': 'phamtuan.newday@gmail.com',
  'comment_on': 'vod',
  'ip': '100.91.73.124',
  'user_fullname': 'Phạm Tuân',
  'publish_status': 1,
  'object_id': '553708d917dc135c8ad7db3f',
  'content': 'hay quá,cười bể bụng',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1431914283,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'a8fbd52808b1403'},
 {'_id': ObjectId('555acdc61a77ce5d65ea074c'),
  'ranking': 0,
  'layer': 0,
  'user_id': 268850,
  'like': 3,
  'user_email': 'elyhien@gmail.com',
  'comment_on': 'vod',
  'ip': '117.6.134.10',
  'user_fullname': 'elyhien@gmail.com',
  'publish_status': 1,
  'object_id': '555565eb17dc132457dfbc65',
  'content': 'hay mà .. mình thích cá tính.cô í',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432014516,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '94e91937a13dc7ab'},
 {'_id': ObjectId('555b38011a77ce5d65ea075f'),
  'ranking': 0,
  'layer': 0,
  'user_id': 250968,
  'like': 0,
  'user_email': 'caominhit123@gmail.com',
  'comment_on': 'vod',
  'ip': '113.176.158.182',
  'user_fullname': 'Cao Minh',
  'publish_status': 0,
  'object_id': '5559900417dc13323d89f9d1',
  'content': 'lồn........... ',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432041944,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 2,
  'device_id': '34cfc68e37683944'},
 {'_id': ObjectId('555b46841a77ce5d65ea0764'),
  'ranking': 0,
  'layer': 0,
  'user_id': 464416,
  'like': 2,
  'user_email': 'kimsunyeon0@gmail.com',
  'comment_on': 'vod',
  'ip': '123.23.62.114',
  'user_fullname': 'Bo Phúng Phíng',
  'publish_status': 1,
  'object_id': '5509370317dc13264573795a',
  'content': 'jessi :* :*',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432045658,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '75800da415d399bc'},
 {'_id': ObjectId('555b52c01a77ce5d65ea0768'),
  'ranking': 0,
  'layer': 0,
  'user_id': 537676,
  'like': 1,
  'user_email': 'johny53801@gmail.com',
  'comment_on': 'vod',
  'ip': '58.186.190.94',
  'user_fullname': 'Tran Ngoc Thach',
  'publish_status': 1,
  'object_id': '555451e717dc130f3eeeea17',
  'content': 'phim quá hay mà ko biết khi nào mới ra tập tiếp',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432048561,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'aa60f069cfb6eb15'},
 {'_id': ObjectId('555b59a31a77ce5d65ea076a'),
  'ranking': 0,
  'layer': 0,
  'user_id': 237725,
  'like': 6,
  'user_email': 'manhthiep@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Manh Thiep Nguyen',
  'publish_status': 1,
  'object_id': '5215971ec969287094465754',
  'content': 'Trang web cho phép sắp xếp các tập theo thứ tự mới nhất, xem nhiều nhất,... hoặc phân trang ra thì tiện hơn. Kiểu hiện tại khó tìm quá :(.',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432050324,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555c50db1a77ce5d65ea078a'),
  'ranking': 0,
  'layer': 0,
  'user_id': 538222,
  'like': 2,
  'user_email': 'itbosco92@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Hội Những Người Mê Phim',
  'publish_status': 1,
  'object_id': '548fb3c717dc130a630b69fc',
  'content': "phim hay wa\\' dien vien tuyet voi ong mat troi.....",
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432113850,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555c8b3d1a77ce78b6068b83'),
  'ranking': 0,
  'layer': 0,
  'user_id': 4524,
  'like': 4,
  'user_email': 'vuluc88@gmail.com',
  'comment_on': 'vod',
  'ip': '1.54.46.242',
  'user_fullname': 'vũ Lực 88',
  'publish_status': 1,
  'object_id': '5453639f17dc1371f538a4cd',
  'content': 'flash yếu bà cố',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432128798,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'dc750d43f3d7889d'},
 {'_id': ObjectId('555d410d1a77ce78b6068ba7'),
  'ranking': 0,
  'layer': 0,
  'user_id': 28,
  'like': 0,
  'user_email': 'lokiheero@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Quốc Trung',
  'publish_status': 0,
  'object_id': '5508eff917dc132642737818',
  'content': 'testtttttttttttttttttttttttt',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432175346,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555d4c341a77ce0234bce2ba'),
  'ranking': 0,
  'layer': 0,
  'user_id': 36,
  'like': 0,
  'user_email': '902stt@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Thiếu nữ 16 tuổi',
  'publish_status': 0,
  'object_id': '5528a81917dc135c88d7d679',
  'content': 'L{}`n t`nh',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432178201,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555d86411a77ce0234bce2df'),
  'ranking': 0,
  'layer': 0,
  'user_id': 539336,
  'like': 3,
  'user_email': 'tuyenltt@gmail.com',
  'comment_on': 'vod',
  'ip': '42.116.8.164',
  'user_fullname': 'Tuyen Le',
  'publish_status': 1,
  'object_id': '5538b0a117dc135c8ad7dbfc',
  'content': 'phim hay',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432193062,
  'device': 'winphone',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'mPgjxpGyynjlSXT2ZJYzp1QiKd9RBmhNZ26hQnPo'},
 {'_id': ObjectId('555e7d8e1a77ce0234bce320'),
  'ranking': 0,
  'layer': 0,
  'user_id': 540178,
  'like': 2,
  'user_email': 'mailien312@gmail.com',
  'comment_on': 'vod',
  'ip': 'null',
  'user_fullname': 'Mai Liên',
  'publish_status': 1,
  'object_id': '55224d6e17dc1367d3b6c03e',
  'content': 'đang đến đoạn hay mà sao nay thứ 6 rùi vẫn chưa lên thế... hi',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432256381,
  'device': 'web-playfpt',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'null'},
 {'_id': ObjectId('555e82701a77ce0234bce321'),
  'ranking': 0,
  'layer': 0,
  'user_id': 488294,
  'like': 5,
  'user_email': 'teovt2001@gmail.com',
  'comment_on': 'vod',
  'ip': '14.163.226.231',
  'user_fullname': 'teovt2001@gmail.com',
  'publish_status': 1,
  'object_id': '5514fd9e17dc135c56f3c605',
  'content': 'sao hay dừng hinh thế',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432257631,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '7f1c5a0196e6128a'},
 {'_id': ObjectId('555e99261a77ce0234bce330'),
  'ranking': 0,
  'layer': 0,
  'user_id': 42,
  'like': 2,
  'user_email': 'chitieuhoang@gmail.com',
  'comment_on': 'event',
  'ip': '42.116.8.164',
  'user_fullname': 'aa',
  'publish_status': 0,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'fnxidnxidndi hsjsnsidkd djdjdd',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432263444,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'd5493829d755e075'},
 {'_id': ObjectId('555e998a1a77ce0234bce333'),
  'ranking': 0,
  'layer': 0,
  'user_id': 42,
  'like': 1,
  'user_email': 'chitieuhoang@gmail.com',
  'comment_on': 'vod',
  'ip': '42.116.8.164',
  'user_fullname': 'aa',
  'publish_status': 1,
  'object_id': '555da9a917dc1321b24f9d4e',
  'content': 'co 2 phan ha',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432263544,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'd5493829d755e075'},
 {'_id': ObjectId('555e9a971a77ce0234bce335'),
  'ranking': 0,
  'layer': 0,
  'user_id': 42,
  'like': 0,
  'user_email': 'chitieuhoang@gmail.com',
  'comment_on': 'vod',
  'ip': '42.116.8.164',
  'user_fullname': 'aa',
  'publish_status': 0,
  'object_id': '555dac9c17dc1321b34f9d60',
  'content': 'jqjavaakbxksgjsvj, jgajgxs',
  'reviewer': 'vuluc88',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432263814,
  'device': 'android',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': 'd5493829d755e075'},
 {'_id': ObjectId('555e9f411a77ce0234bce33e'),
  'ranking': 0,
  'layer': 0,
  'user_id': 540248,
  'like': 1,
  'user_email': 'emtoi@gmail.com',
  'comment_on': 'event',
  'ip': '118.68.240.45',
  'user_fullname': 'emtoi@gmail.com',
  'publish_status': 1,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'Tieng hat mai xanh',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432265009,
  'device': 'ios',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '27DA5938-8D03-4DCD-B3CE-2B7E70E5886C'},
 {'_id': ObjectId('555ea5001a77ce0234bce347'),
  'ranking': 0,
  'layer': 0,
  'user_id': 540252,
  'like': 0,
  'user_email': 'xuanxua@gmail.com',
  'comment_on': 'event',
  'ip': '118.68.240.45',
  'user_fullname': 'xuanxua@gmail.com',
  'publish_status': 0,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'Chivvy fvcfhv¥|{%*|%+*',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432266480,
  'device': 'ios',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '27159624-9855-4F8C-A30E-D95040058987'},
 {'_id': ObjectId('555ea5391a77ce0234bce349'),
  'ranking': 0,
  'layer': 0,
  'user_id': 540252,
  'like': 4,
  'user_email': 'xuanxua@gmail.com',
  'comment_on': 'event',
  'ip': '118.68.240.45',
  'user_fullname': 'xuanxua@gmail.com',
  'publish_status': 0,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'Chivvy fvcfhv¥|{%*|%+*',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432266537,
  'device': 'ios',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '27159624-9855-4F8C-A30E-D95040058987'},
 {'_id': ObjectId('555eafb81a77ce0234bce35a'),
  'ranking': 0,
  'layer': 0,
  'user_id': 342609,
  'like': 1,
  'user_email': 'phamkhang@gmail.com',
  'comment_on': 'event',
  'ip': '42.116.8.164',
  'user_fullname': 'a Khang',
  'publish_status': 0,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'Gg gg gfg',
  'reviewer': 'phongnq',
  'report_count': 0,
  'review_status': 1,
  'timestamp': 1432269223,
  'device': 'ios',
  'report_reason': [],
  'dislike': 0,
  'comment_status': 0,
  'device_id': '0EDB3983-8AAC-44EA-B03C-A9324A4ACA74'},
 {'_id': ObjectId('555eb1e61a77ce0234bce35d'),
  'ranking': 0,
  'layer': 0,
  'user_id': 342609,
  'like': 2,
  'user_email': 'phamkhang@gmail.com',
  'comment_on': 'event',
  'ip': '42.116.8.164',
  'user_fullname': 'a Khang',
  'publish_status': 0,
  'object_id': '552b76a417dc135c89d7d704',
  'content': 'Fff ffff gg ggf',

In [9]:
df = pd.DataFrame(list_cur)

In [10]:
df.head()

,_id,ranking,layer,user_id,like,user_email,comment_on,ip,user_fullname,publish_status,...,content,reviewer,report_count,review_status,timestamp,device,report_reason,dislike,comment_status,device_id
0,555466761a77ce5d65ea062a,0,0,12,1,hoaianh2210@gmail.com,event,null,Nguyễn Hoài Anh,1,...,"Chương trình \ Tuyệt cú mèo\ luôn, chờ lâu rồi...",gianpt,0,1,1431595030,web-playfpt,[],0,0,null
1,555457bf1a77ce5d65ea0617,0,0,130,5,gian.phan@gmail.com,event,null,Phan Thanh Gian,1,...,Chờ đợi chương trình này đã lâu! Hẹn mọi người...,gianpt,0,1,1431591263,web-playfpt,[],0,0,null
2,555413001a77ce5d65ea0609,0,0,527201,0,cloudytang@gmail.com,vod,42.116.8.164,Đàm Ngọc Vân,0,...,comment cai,vuluc88,0,1,1431573662,android,[],0,2,983b5151a74de256
3,555357f71a77ce5d65ea0606,0,0,424467,1,n_x_cuong@yahoo.com,vod,null,nguyen xuan cuong,1,...,"lồng tiếng mà như tập đọc, nghe không nuốt nổi...",vuluc88,0,1,1431525776,web-playfpt,[],0,0,null
4,555491181a77ce5d65ea0636,0,0,805,12,lequy1579@gmail.com,vod,42.117.66.148,Quang Quỳnh Lê,1,...,Phim rất hay ;),vuluc88,0,1,1431605947,android,[],0,0,2e190e1227743c0d

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885169 entries, 0 to 885168
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   _id             885169 non-null  object
 1   ranking         885169 non-null  int64
 2   layer           885169 non-null  int64
 3   user_id         885169 non-null  int64
 4   like            885169 non-null  int64
 5   user_email      885169 non-null  object
 6   comment_on      885169 non-null  object
 7   ip              885169 non-null  object
 8   user_fullname   885169 non-null  object
 9   publish_status  885169 non-null  int64
 10  object_id       885169 non-null  object
 11  content         885169 non-null  object
 12  reviewer        885169 non-null  object
 13  report_count    885169 non-null  int64
 14  review_status   885169 non-null  int64
 15  timestamp       885169 non-null  int64
 16  device          885169 non-null  object
 17  report_reason   885169 non-null  object
 18  dislike         885169 non-null  int64
 19  comment_status  885169 non-null  int64
 20  device_id       885169 non-null  object
dtypes: int64(10), object(11)
memory usage: 141.8+ MB

In [ ]:
#Remove unused columns
df = df.drop([ 
'ranking','layer','like','user_email','user_fullname','reviewer','report_count',
'review_status','report_reason','dislike','comment_status','device_id', 
'_id'], axis=1)

In [13]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [14]:
df.head()

,user_id,comment_on,ip,publish_status,object_id,content,timestamp,device
0,12,event,null,1,552b2f0817dc135c89d7d6a2,"Chương trình \ Tuyệt cú mèo\ luôn, chờ lâu rồi...",1970-01-01 00:00:01.431595030,web-playfpt
1,130,event,null,1,552b2f0817dc135c89d7d6a2,Chờ đợi chương trình này đã lâu! Hẹn mọi người...,1970-01-01 00:00:01.431591263,web-playfpt
2,527201,vod,42.116.8.164,0,5453639f17dc1371f538a4cd,comment cai,1970-01-01 00:00:01.431573662,android
3,424467,vod,null,1,551a43b417dc135c58f3c691,"lồng tiếng mà như tập đọc, nghe không nuốt nổi...",1970-01-01 00:00:01.431525776,web-playfpt
4,805,vod,42.117.66.148,1,5549cace17dc132a0cee1801,Phim rất hay ;),1970-01-01 00:00:01.431605947,android

Pre-trained PhoBERT Model

In [13]:
pip install transformers torch

Requirement already satisfied: transformers in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (4.45.2)
Requirement already satisfied: torch in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (2.5.0)
Requirement already satisfied: filelock in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.26.1)
Requirement already satisfied: numpy>=1.17 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.1.1)
Requirement already satisfied: packaging>=20.0 in c:\users\da admin\appdata\roaming\python\python312\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.20.1)
Requirement already satisfied: tqdm>=4.27 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (2024.10.0)
Requirement already satisfied: setuptools in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\da admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\da admin\appdata\local\programs\python\python312\lib\site-packages (from requests->transformers) (2024.7.4)
Note: you may need to restart the kernel to use updated packages.

In [14]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

c:\Users\DA Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
#Load pre-trained model
model = AutoModelForSequenceClassification.from_pretrained("wonrax/phobert-base-vietnamese-sentiment")

#Load Tokenizer from model 
tokenizer = AutoTokenizer.from_pretrained("wonrax/phobert-base-vietnamese-sentiment")

In [18]:
#Test
sentence = 'coi phim buồn mấy cũng phải cười vỡ bụng'

input_ids = torch.tensor([tokenizer.encode(sentence, add_special_tokens=True)])

with torch.no_grad():
    out = model(input_ids)
    print(pd.Series(out.logits.softmax(dim=-1).tolist()[0], index = ['NEG', 'POS', 'NEU']))

NEG    0.984004
POS    0.005342
NEU    0.010653
dtype: float64

In [ ]:
#Create a function to use the model: 0-negative, 1-positive, and 2-neutral or undetermined.
def sentiment(sentence):
    try:
        input_ids = tokenizer.encode(sentence, truncation=True, max_length= tokenizer.model_max_length)
        print(f"Encoded sentence: {input_ids}")  
    except Exception as e:
        print(f"Error encoding sentence: {e}")
        return 2 
    
    input_ids = torch.tensor([input_ids])
    if input_ids.shape[1] > tokenizer.model_max_length:
        print("Input sentence exceeds maximum length.")
        return 2
    with torch.no_grad():
        out = model(input_ids)
        sentiment_score = np.argmax(out.logits.softmax(dim=-1).tolist()[0])
        print(f"Predicted sentiment: {sentiment_score}")  
        return sentiment_score

In [ ]:
df_small = df.copy()
df_small.loc[:, 'sentiment_score'] = df_small['content'].apply(sentiment)

Encoded sentence: [0, 6041, 1893, 23200, 20477, 19002, 1486, 1387, 9367, 1672, 23200, 3198, 6281, 1301, 4, 971, 700, 182, 60, 10, 100, 49033, 1384, 4, 23309, 23309, 2]
Predicted sentiment: 1
Encoded sentence: [0, 11566, 2905, 5887, 1893, 23, 14, 39396, 1881, 381, 29098, 207, 18, 878, 136, 219, 1556, 12092, 34, 4062, 13074, 2008, 4827, 5, 2]
Predicted sentiment: 1
Encoded sentence: [0, 17455, 14760, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4513, 355, 64, 42, 834, 3438, 18020, 1395, 4, 523, 17, 6295, 33379, 1384, 4, 774, 1746, 1294, 50, 3438, 25, 359, 551, 48, 2]
Predicted sentiment: 0
Encoded sentence: [0, 3880, 1698, 10440, 45729, 1204, 118, 58679, 19, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2859, 31827, 5516, 5942, 983, 2]
Predicted sentiment: 1
Encoded sentence: [0, 118, 1981, 20222, 2075, 1981, 20222, 2161, 236, 3, 3, 3, 381, 7593, 37272, 37272, 19, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4014, 3288, 9164, 9164, 9164, 9164, 13846, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 118, 2845, 12584, 305, 43795, 2]
Predicted sentiment: 2
Encoded sentence: [0, 266, 118, 5109, 1894, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4413, 102, 10, 54159, 384, 957, 10013, 2]
Predicted sentiment: 2
Encoded sentence: [0, 1672, 1664, 10601, 5474, 2158, 266, 118, 2]
Predicted sentiment: 1
Encoded sentence: [0, 204, 33841, 4, 2947, 2049, 47036, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1698, 241, 118, 6, 7130, 376, 7593, 37272, 19, 2]
Predicted sentiment: 1
Encoded sentence: [0, 5530, 21697, 64, 1947, 13778, 1938, 51744, 10448, 1659, 57728, 2029, 29858, 94, 3763, 20094, 9428, 3808, 2]
Predicted sentiment: 2
Encoded sentence: [0, 118, 20027, 10959, 944, 4455, 1569, 2]
Predicted sentiment: 0
Encoded sentence: [0, 118, 64, 3457, 68, 543, 569, 14243, 17959, 106, 8210, 2]
Predicted sentiment: 1
Encoded sentence: [0, 55188, 1301, 58861, 135, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2545, 57430, 7593, 1497, 7593, 1497, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 204, 118, 64, 5516, 55, 26, 142, 60, 40, 834, 917, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2490, 5568, 13, 996, 984, 1666, 9, 834, 63, 129, 385, 60, 34889, 1187, 4, 305, 36, 34889, 1187, 10959, 135, 151, 1389, 751, 40, 54, 5959, 31536, 10557, 8733, 380, 35, 359, 240, 204, 7593, 14157, 5, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 118, 25451, 57307, 104, 3173, 2052, 4104, 2052, 21443, 4129, 3843, 2662, 25463, 6447, 1384, 36588, 2]
Predicted sentiment: 1
Encoded sentence: [0, 11705, 1783, 155, 2105, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1187, 8475, 9164, 9164, 9164, 9164, 9164, 9164, 9164, 9164, 9164, 9164, 9164, 13846, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1042, 3, 3, 55409, 1677, 1187, 55409, 5976, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 118, 2]
Predicted sentiment: 1
Encoded sentence: [0, 52, 30, 687, 118, 64, 423, 136, 129, 245, 1698, 16174, 74, 102, 72, 30218, 135, 9599, 2]
Predicted sentiment: 2
Encoded sentence: [0, 423, 118, 772, 1340, 7274, 570, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1866, 1301, 1600, 3385, 1301, 1600, 3385, 1301, 4453, 1340, 1302, 2545, 1302, 27978, 3385, 1493, 2158, 1236, 2545, 1236, 2545, 1236, 2158, 2]
Predicted sentiment: 2
Encoded sentence: [0, 3005, 76, 35019, 953, 2]
Predicted sentiment: 2
Encoded sentence: [0, 2545, 6539, 34328, 1850, 3796, 1388, 1600, 14453, 1529, 2545, 1302, 1659, 2545, 4, 2545, 10931, 2545, 1529, 1600, 1118, 2]
Predicted sentiment: 0
Encoded sentence: [0, 4826, 16030, 38902, 3189, 656, 2]
Predicted sentiment: 1
Encoded sentence: [0, 5845, 1659, 25878, 1866, 1659, 1395, 1866, 1340, 1659, 3, 3, 3, 52513, 56688, 3, 52513, 4816, 1497, 2]
Predicted sentiment: 1
Encoded sentence: [0, 5845, 1659, 25878, 1866, 1659, 1395, 1866, 1340, 1659, 3, 3, 3, 52513, 56688, 3, 52513, 4816, 1497, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1276, 2302, 26091, 1529, 1866, 2302, 2]
Predicted sentiment: 2
Encoded sentence: [0, 1579, 9016, 6313, 9016, 26091, 13724, 3961, 2]
Predicted sentiment: 2
Encoded sentence: [0, 5516, 305, 1236, 1894, 28406, 11117, 7403, 266, 21688, 2644, 42524, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 2]
Predicted sentiment: 1
Encoded sentence: [0, 35, 423, 68, 305, 1947, 11, 46924, 1581, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 19271, 1298, 1617, 4572, 50, 102, 243, 406, 5839, 6106, 1464, 232, 64, 55, 24, 328, 23200, 406, 106, 1301, 50410, 23200, 2859, 204, 23196, 37272, 19, 2]
Predicted sentiment: 0
Encoded sentence: [0, 2839, 28852, 36, 64, 24, 2576, 3872, 1300, 10152, 94, 35544, 4, 423, 5779, 5516, 1224, 40, 36, 119, 13, 5959, 15, 21, 215, 28852, 363, 57894, 5, 2]
Predicted sentiment: 2
Encoded sentence: [0, 5779, 9479, 1384, 4, 834, 1830, 819, 42, 45, 1210, 182, 21299, 7593, 20, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1746, 1294, 560, 3686, 570, 45110, 4, 834, 163, 273, 48767, 7, 266, 142, 33, 46924, 1581, 114, 667, 2657, 2665, 148, 351, 2]
Predicted sentiment: 0
Encoded sentence: [0, 28852, 118, 2]
Predicted sentiment: 1
Encoded sentence: [0, 7742, 118, 520, 6955, 2]
Predicted sentiment: 2
Encoded sentence: [0, 17, 10, 355, 3808, 47036, 2]
Predicted sentiment: 0
Encoded sentence: [0, 118, 9052, 1236, 10448, 2]
Predicted sentiment: 0
Encoded sentence: [0, 2667, 2662, 38902, 37082, 2]
Predicted sentiment: 1
Encoded sentence: [0, 3907, 60900, 25093, 45729, 2795, 485, 48, 7220, 58216, 2008, 4, 34, 37962, 2162, 15641, 1765, 4, 6363, 60198, 1677, 5109, 3, 1947, 3907, 60900, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1487, 1656, 18050, 9052, 2]
Predicted sentiment: 0
Encoded sentence: [0, 423, 44, 274, 230, 12907, 9534, 1698, 14876, 1384, 10959, 46, 73, 774, 5516, 10, 12907, 9534, 987, 202, 2127, 16649, 18206, 5618, 236, 43074, 1085, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1395, 4908, 2545, 1387, 1301, 1659, 1894, 2]
Predicted sentiment: 1
Encoded sentence: [0, 6539, 13403, 6745, 1881, 1384, 4967, 11245, 2423, 1236, 1866, 4908, 2545, 1493, 33375, 1791, 1600, 1395, 1659, 1388, 43585, 599, 2]
Predicted sentiment: 0
Encoded sentence: [0, 423, 224, 23, 5516, 10, 1626, 3796, 2545, 49733, 1581, 7086, 18773, 12384, 3855, 7376, 1546, 5365, 9474, 3214, 5381, 22168, 1751, 3012, 2147, 5003, 2326, 2186, 6132, 15823, 1854, 57968, 57968, 3, 2]
Predicted sentiment: 2
Encoded sentence: [0, 1947, 774, 1236, 1894, 5779, 13373, 2]
Predicted sentiment: 2
Encoded sentence: [0, 3005, 3492, 4219, 15866, 118, 2]
Predicted sentiment: 1
Encoded sentence: [0, 3000, 80, 4263, 808, 2104, 15, 1362, 1889, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4190, 202, 409, 75, 3787, 3777, 2]
Predicted sentiment: 0
Encoded sentence: [0, 520, 8, 118, 204, 1027, 204, 27979, 1187, 58861, 73, 3053, 339, 12, 73, 44530, 1850, 55897, 34976, 18302, 2127, 6992, 339, 12, 18302, 54990, 55897, 224, 57307, 359, 56476, 1881, 23200, 25, 97, 8, 224, 57307, 118, 23200, 12, 215, 266, 2]
Predicted sentiment: 0
Encoded sentence: [0, 6363, 1894, 21688, 3907, 4129, 2008, 11855, 2801, 1510, 17218, 7453, 245, 5516, 2]
Predicted sentiment: 1
Encoded sentence: [0, 20014, 1329, 2008, 22535, 26115, 51, 74, 281, 48, 266, 14053, 2]
Predicted sentiment: 2
Encoded sentence: [0, 305, 28852, 23, 2859, 2859, 7593, 3482, 2]
Predicted sentiment: 1
Encoded sentence: [0, 423, 227, 834, 99, 40, 54, 17, 10, 834, 142, 10, 18808, 48767, 702, 2545, 49733, 1581, 7086, 18773, 1556, 6825, 1551, 12894, 7757, 4917, 2326, 5365, 2147, 2873, 1751, 3012, 2147, 2617, 2186, 1556, 3214, 10421, 1551, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 5516, 40, 148, 2]
Predicted sentiment: 0
Encoded sentence: [0, 39, 219, 5530, 1637, 30, 1664, 8, 774, 1947, 51744, 702, 1301, 9367, 57728, 25052, 204, 57, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1981, 3148, 51899, 1118, 1517, 18707, 3587, 48512, 52349, 15769, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1581, 1850, 1850, 1850, 1850, 135, 44, 10, 14620, 11804, 1850, 1850, 26194, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2029, 1494, 3535, 224, 266, 2]
Predicted sentiment: 0
Encoded sentence: [0, 423, 1947, 305, 3438, 1947, 2008, 20660, 2]
Predicted sentiment: 2
Encoded sentence: [0, 42, 1494, 5460, 241, 3808, 2]
Predicted sentiment: 0
Encoded sentence: [0, 10, 36, 24153, 1893, 305, 44, 17, 11, 34976, 1790, 5779, 4762, 4578, 2]
Predicted sentiment: 0
Encoded sentence: [0, 204, 33841, 381, 8840, 5135, 592, 570, 1494, 13572, 1387, 135, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1117, 14400, 94, 2067, 298, 2648, 4841, 7593, 19, 26090, 5516, 5942, 983, 2]
Predicted sentiment: 1
Encoded sentence: [0, 925, 834, 54, 41, 2]
Predicted sentiment: 2
Encoded sentence: [0, 453, 10, 849, 834, 917, 5713, 2811, 114, 3020, 834, 38200, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 118, 4116, 4453, 953, 2]
Predicted sentiment: 2
Encoded sentence: [0, 423, 3206, 1340, 7274, 1565, 878, 35702, 3535, 5779, 2]
Predicted sentiment: 2
Encoded sentence: [0, 2260, 48929, 18612, 60198, 1111, 7220, 2094, 2]
Predicted sentiment: 2
Encoded sentence: [0, 18808, 48767, 10, 34, 31167, 5796, 2586, 266, 118, 204, 1027, 3198, 6281, 9965, 23309, 48767, 485, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2029, 29858, 4803, 9052, 1947, 1388, 1947, 1388, 1664, 20093, 305, 1236, 1894, 13233, 6447, 1111, 2]
Predicted sentiment: 2
Encoded sentence: [0, 7249, 834, 60, 700, 204, 5779, 2]
Predicted sentiment: 0
Encoded sentence: [0, 47292, 58216, 1677, 8825, 58216, 1231, 118, 29243, 45729, 13208, 3164, 6281, 60198, 1111, 1924, 5109, 60198, 1517, 6265, 2]
Predicted sentiment: 2
Encoded sentence: [0, 2565, 68, 305, 9, 28852, 7, 54473, 8656, 19804, 108, 230, 355, 96, 7, 1362, 1889, 59, 22279, 4, 230, 2226, 2106, 7, 28852, 54, 44, 2225, 5, 503, 4623, 91, 2301, 1981, 2308, 2226, 2106, 7, 68, 10, 12053, 1294, 11942, 114, 3000, 175, 26913, 2]
Predicted sentiment: 2
Encoded sentence: [0, 3, 62956, 57768, 3, 61562, 61545, 60570, 2]
Predicted sentiment: 1
Encoded sentence: [0, 8216, 45729, 1204, 1698, 10440, 45729, 1204, 33841, 34976, 1698, 10440, 45729, 1204, 22785, 9446, 58216, 1677, 6221, 60198, 1387, 135, 2]
Predicted sentiment: 1
Encoded sentence: [0, 38902, 118, 89, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1340, 2545, 1340, 1340, 1340, 1340, 1340, 1340, 1340, 1340, 1340, 2545, 2545, 2545, 2545, 2545, 2545, 23321, 1493, 2545, 2545, 1340, 1340, 1340, 1340, 2545, 2545, 2545, 2545, 1659, 1529, 1866, 33600, 1866, 2545, 1866, 1340, 1866, 1493, 1600, 2545, 1340, 1340, 1600, 1395, 2545, 1529, 2545, 1340, 2545, 2545, 1493, 1866, 2545, 13724, 2545, 1340, 1340, 2545, 23321, 2029, 7306, 1672, 6040, 6040, 1672, 6040, 6040, 7306, 11245, 21431, 1487, 7306, 7306, 7306, 1672, 6040, 12945, 2]
Predicted sentiment: 1
Encoded sentence: [0, 5276, 10965, 258, 443, 35597, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4444, 306, 46, 1201, 2]
Predicted sentiment: 2
Encoded sentence: [0, 7828, 525, 23716, 1187, 10959, 819, 284, 258, 10, 184, 7249, 1220, 48, 246, 15, 36, 49769, 10959, 9, 751, 984, 1666, 281, 9270, 1600, 22095, 1301, 10959, 240, 266, 59, 37289, 2586, 240, 63, 129, 385, 2358, 3306, 11727, 8, 1580, 67, 2]
Predicted sentiment: 2
Encoded sentence: [0, 423, 17, 10, 834, 1395, 18800, 1384, 114, 2]
Predicted sentiment: 0
Encoded sentence: [0, 33600, 2545, 1236, 1493, 1866, 2545, 1659, 4323, 1395, 1866, 1236, 3482, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4006, 3198, 1510, 20093, 2008, 3587, 2]
Predicted sentiment: 2
Encoded sentence: [0, 3753, 1384, 1579, 1340, 1866, 1340, 23321, 3961, 2]
Predicted sentiment: 2
Encoded sentence: [0, 3880, 118, 89, 2]
Predicted sentiment: 1
Encoded sentence: [0, 3486, 57, 57123, 23653, 14453, 3, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1302, 29107, 1388, 1301, 1659, 1866, 27950, 2]
Predicted sentiment: 1
Encoded sentence: [0, 3000, 475, 2198, 7, 1842, 3882, 10838, 21310, 870, 1565, 27372, 229, 5516, 10, 4263, 11796, 7, 1362, 46924, 1187, 4, 373, 219, 142, 32, 19652, 19652, 5516, 385, 50854, 1301, 4, 10, 3688, 91, 35783, 7833, 77, 5516, 50, 373, 385, 8249, 18014, 12584, 2]
Predicted sentiment: 0
Encoded sentence: [0, 266, 118, 26116, 2]
Predicted sentiment: 2
Encoded sentence: [0, 5516, 305, 1236, 1395, 3, 2]
Predicted sentiment: 0
Encoded sentence: [0, 2545, 10588, 10588, 2545, 4014, 25399, 26898, 2]
Predicted sentiment: 0
Encoded sentence: [0, 4080, 17104, 2404, 6928, 523, 50, 108, 7130, 376, 155, 1687, 23, 30974, 5015, 20027, 5, 2]
Predicted sentiment: 0
Encoded sentence: [0, 40168, 6851, 1384, 43663, 43376, 29464, 28862, 4917, 31157, 27978, 1494, 2545, 4660, 2586, 1340, 1187, 6525, 1626, 175, 224, 2]
Predicted sentiment: 1
Encoded sentence: [0, 423, 85, 23420, 204, 33629, 19026, 2]
Predicted sentiment: 1
Encoded sentence: [0, 7220, 7220, 7220, 7220, 9599, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 23, 1464, 26567, 834, 702, 9, 88, 3, 3, 2]
Predicted sentiment: 1
Encoded sentence: [0, 19684, 423, 8738, 2292, 44693, 64, 40, 42993, 27243, 3535, 2]
Predicted sentiment: 2
Encoded sentence: [0, 204, 3518, 41120, 2]
Predicted sentiment: 1
Encoded sentence: [0, 33504, 9866, 700, 204, 2]
Predicted sentiment: 0
Encoded sentence: [0, 5135, 2845, 25879, 84, 59162, 2]
Predicted sentiment: 1
Encoded sentence: [0, 4604, 1565, 7668, 6539, 1894, 3040, 6010, 381, 3763, 2049, 18050, 2161, 1347, 3288, 381, 2]
Predicted sentiment: 0
Encoded sentence: [0, 7298, 2106, 5461, 81, 8973, 563, 9534, 229, 59, 208, 2]
Predicted sentiment: 1
Encoded sentence: [0, 2029, 1494, 55897, 3777, 2]
Predicted sentiment: 0
Encoded sentence: [0, 14171, 31827, 11155, 2]
Predicted sentiment: 1
Encoded sentence: [0, 118, 204, 236, 2]
Predicted sentiment: 1
Encoded sentence: [0, 118, 1582, 47, 1895, 4453, 9, 88, 2]
Predicted sentiment: 2
Encoded sentence: [0, 47, 1895, 57, 240, 277, 37, 563, 68, 4684, 13553, 6620, 1556, 31900, 2]
Predicted sentiment: 2
Encoded sentence: [0, 423, 700, 10, 834, 613, 204, 46924, 1581, 4, 2905, 266, 64, 48, 94, 2905, 372, 18014, 1850, 381, 2]
Predicted sentiment: 1
Encoded sentence: [0, 423, 1947, 7249, 23825, 57, 1659, 10440, 55479, 1231, 5779, 2]
Predicted sentiment: 1
Encoded sentence: [0, 6147, 5696, 1556, 10660, 1656, 2]
Predicted sentiment: 2
Encoded sentence: [0, 1790, 44794, 7304, 2662, 20080, 136, 10042, 4824, 2]
Predicted sentiment: 0
Encoded sentence: [0, 202, 96, 75, 193, 278, 2057, 64, 423, 37289, 10959, 3, 611, 11, 595, 1273, 409, 193, 3972, 278, 28818, 26115, 3, 70, 413, 3787, 4, 807, 20768, 8, 70, 2057, 3787, 10959, 3, 278, 413, 359, 30143, 1384, 4, 611, 300, 1855, 3218, 605, 2]
Predicted sentiment: 1
Encoded sentence: [0, 36695, 204, 17, 774, 11, 10573, 10013, 2]
Predicted sentiment: 0
Encoded sentence: [0, 3698, 1294, 654, 136, 57307, 5600, 101, 1101, 3438, 56630, 23200, 14, 6850, 44, 13, 70, 36, 4263, 1600, 10615, 21473, 453, 66, 8, 515, 101, 64, 94, 119, 877, 52643, 1301, 4, 119, 56096, 52643, 1301, 4, 135, 1101, 111, 8, 61, 16316, 9069, 67, 7, 1850, 18109, 157, 35477, 8957, 38, 11, 1101, 111, 193, 703, 94, 110, 56417, 1384, 4, 11, 1101, 111, 193, 6, 81, 193, 30, 207, 189, 34, 570, 681, 135, 2]
Predicted sentiment: 1
Encoded sentence: [0, 670, 11, 381, 2]
Predicted sentiment: 2
Encoded sentence: [0, 2679, 15506, 21, 18, 57307, 4588, 2263, 170, 2162, 13170, 1301, 23200, 54, 18, 37, 60, 520, 61, 463, 37367, 18109, 2590, 657, 148, 17, 2665, 37096, 1701, 4, 2665, 7594, 8, 86, 14, 47, 11, 184, 148, 13, 176, 24350, 1384, 4, 183, 102, 54, 6430, 343, 86, 32, 47, 11, 184, 148, 37, 13, 3931, 4181, 26427, 4, 64, 50, 74, 102, 47, 11, 148, 54, 468, 148, 86, 32, 14, 47, 49, 24, 385, 695, 235, 618, 1182, 26427, 5, 669, 60, 8, 28898, 2845, 4985, 381, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1746, 1294, 834, 173, 45, 3399, 1698, 14876, 1384, 4, 1294, 12813, 2753, 5916, 2833, 39468, 2]
Predicted sentiment: 0
Encoded sentence: [0, 203, 2271, 25, 602, 64, 41, 3057, 6866, 25, 1638, 732, 57, 570, 7593, 19, 2]
Predicted sentiment: 0
Encoded sentence: [0, 266, 118, 89, 6447, 1384, 95, 10081, 1656, 1581, 7306, 31311, 89, 4116, 853, 28565, 4219, 10660, 5791, 7873, 19379, 3, 2006, 83, 5329, 2380, 10242, 2662, 1820, 41619, 59162, 811, 20093, 37217, 2644, 10322, 759, 35019, 3173, 2052, 7430, 1384, 7593, 37272, 37272, 3, 2]
Predicted sentiment: 1
Encoded sentence: [0, 423, 227, 834, 99, 40, 54, 17, 10, 834, 142, 10, 18808, 48767, 702, 2545, 49733, 1581, 7086, 18773, 1556, 6825, 1551, 12894, 7757, 4917, 2326, 5365, 2147, 2873, 1751, 3012, 2147, 2617, 2186, 1556, 3214, 10421, 1551, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 423, 266, 23, 17, 380, 437, 834, 702, 47036, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 5530, 21697, 11076, 1701, 4, 17, 305, 11, 224, 148, 351, 7593, 14157, 14157, 20, 2]
Predicted sentiment: 0
Encoded sentence: [0, 2811, 599, 1626, 44, 48767, 20256, 68, 224, 60, 305, 10, 2125, 127, 108, 1626, 560, 560, 423, 241, 76, 805, 1401, 80, 4422, 64, 11050, 6922, 5262, 4, 1187, 7390, 2586, 2545, 49733, 1581, 7086, 18773, 1556, 8640, 1546, 11382, 1556, 11485, 10313, 11382, 28024, 1751, 3012, 2147, 2617, 1625, 8172, 2789, 25534, 2]
Predicted sentiment: 0
Encoded sentence: [0, 423, 17, 2479, 60455, 25093, 45729, 2795, 1659, 10440, 55479, 31829, 2457, 7220, 58216, 5976, 17, 1850, 61538, 2]
Predicted sentiment: 1
Encoded sentence: [0, 73, 266, 59162, 16295, 1236, 6252, 12728, 19301, 3342, 2380, 2644, 1340, 4129, 1236, 6252, 4, 39245, 2008, 3587, 485, 4453, 1387, 2545, 5976, 774, 1340, 4129, 5172, 1111, 1866, 25386, 13373, 2]
Predicted sentiment: 2
Encoded sentence: [0, 614, 5530, 21697, 101, 23, 231, 658, 423, 6992, 8958, 33660, 348, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1340, 1340, 1340, 1659, 1659, 14299, 6313, 6313, 1866, 1340, 2545, 2545, 23321, 1493, 21344, 2545, 13724, 13724, 1866, 55032, 1529, 2545, 23321, 23321, 1529, 6313, 14299, 10619, 2]
Predicted sentiment: 1
Encoded sentence: [0, 266, 118, 2586, 293, 118, 5932, 3070, 114, 2]
Predicted sentiment: 2
Encoded sentence: [0, 118, 38937, 60455, 2]
Predicted sentiment: 0
Encoded sentence: [0, 423, 5516, 3005, 18808, 3611, 2380, 118, 2081, 16030, 2545, 1664, 1340, 4129, 697, 2]
Predicted sentiment: 2
Encoded sentence: [0, 523, 1447, 17, 5132, 5, 17, 108, 819, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1294, 12813, 919, 33504, 9866, 2]
Predicted sentiment: 0
Encoded sentence: [0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2]
Predicted sentiment: 1
Encoded sentence: [0, 11693, 2052, 718, 20093, 305, 3438, 18377, 1236, 1894, 2644, 1118, 2]
Predicted sentiment: 0
Encoded sentence: [0, 266, 4444, 1493, 45054, 50, 5516, 2]
Predicted sentiment: 2
Encoded sentence: [0, 41484, 43230, 3773, 52886, 7806, 1765, 31, 1579, 48586, 2406, 19727, 2228, 11664, 3, 55419, 15713, 58252, 6851, 33793, 3164, 5329, 29464, 16540, 1347, 57968, 1659, 23196, 2147, 21718, 1579, 2305, 1494, 1551, 6232, 5188, 2]
Predicted sentiment: 1
Encoded sentence: [0, 39245, 136, 25888, 8013, 2]
Predicted sentiment: 2
Encoded sentence: [0, 26, 142, 10, 230, 76, 570, 5779, 2]
Predicted sentiment: 1
Encoded sentence: [0, 1464, 232, 60, 10, 834, 917, 63, 702, 2]
Predicted sentiment: 2
Encoded sentence: [0, 1031, 1362, 31827, 55188, 1301, 3, 982, 56301, 1889, 2]
Predicted sentiment: 0
Encoded sentence: [0, 118, 42, 224, 1494, 3, 14876, 3, 1677, 2]
Predicted sentiment: 0
Encoded sentence: [0, 1622, 5460, 1302, 29107, 1302, 4908, 1302, 29107, 1302, 1236, 2302, 2]
Predicted sentiment: 1
Encoded sentence: [0, 3, 5460, 1302, 1236, 1493, 1659, 1529, 19849, 1529, 19849, 1529, 19849, 1529, 19849, 20871, 2]
Predicted sentiment: 0
Encoded sentence: [0, 7304, 1881, 1881, 1384, 1384, 1340, 1340, 13724, 2302, 2]
Predicted sentiment: 2
Encoded sentence: [0, 51859, 1387, 4, 1555, 27481, 5213, 1111, 15769, 10865, 246, 5301, 1347, 5, 1555, 1931, 246, 1387, 26952, 10865, 40982, 1581, 52285, 5, 1555, 1493, 28939, 33793, 51899, 6618, 1517, 2127, 4942, 18526, 5, 30045, 1622, 3777, 2]
Predicted sentiment: 1
Encoded sentence: [0, 56537, 59285, 60647, 57388, 62197, 56537, 58259, 3, 2]
Predicted sentiment: 1

In [ ]:
df_small.to_csv('output.csv', index=False)